//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace OrderingApp.EntityClasses
{
	/// <summary>Class which represents the entity 'OrderItem'.</summary>
	public partial class OrderItem : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="OrderItem"/> class.</summary>
		public OrderItem() : base()
		{
			OnCreated();
		}

		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the OrderId field. </summary>
		public System.Int32 OrderId { get; set; }
		/// <summary>Gets or sets the ProductId field. </summary>
		public System.Int32 ProductId { get; set; }
		/// <summary>Gets or sets the Quantity field. </summary>
		public Nullable<System.Int32> Quantity { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'OrderItem.Order - Order.OrderItems (m:1)'</summary>
		public virtual Order Order { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'OrderItem.Product - Product.OrderItems (m:1)'</summary>
		public virtual Product Product { get; set; } = null!;
	}
}
